//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
